package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	private Integer goodsId;
	private Integer maijiaId;
	private String goodsName;
	private String goodsMiaoshu;

	private String goodsPic;
	private Integer goodsShichangjia;
	private Integer goodsTejia;
	private String goodsIsnottejia;
	
	private Integer goodsCatelogId;
	private String shifoumaichu;
	private String goodsDel;
	
	
	public Integer getGoodsId()
	{
		return goodsId;
	}
	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}
	public String getGoodsName()
	{
		return goodsName;
	}
	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}
	public String getGoodsMiaoshu()
	{
		return goodsMiaoshu;
	}
	public void setGoodsMiaoshu(String goodsMiaoshu)
	{
		this.goodsMiaoshu = goodsMiaoshu;
	}
	
	public Integer getMaijiaId() {
		return maijiaId;
	}
	public void setMaijiaId(Integer maijiaId) {
		this.maijiaId = maijiaId;
	}
	public String getShifoumaichu() {
		return shifoumaichu;
	}
	public void setShifoumaichu(String shifoumaichu) {
		this.shifoumaichu = shifoumaichu;
	}
	public String getGoodsPic()
	{
		return goodsPic;
	}
	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}
	public Integer getGoodsShichangjia()
	{
		return goodsShichangjia;
	}
	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}
	public Integer getGoodsTejia()
	{
		return goodsTejia;
	}
	public void setGoodsTejia(Integer goodsTejia)
	{
		this.goodsTejia = goodsTejia;
	}
	public String getGoodsIsnottejia()
	{
		return goodsIsnottejia;
	}
	public void setGoodsIsnottejia(String goodsIsnottejia)
	{
		this.goodsIsnottejia = goodsIsnottejia;
	}
	public Integer getGoodsCatelogId()
	{
		return goodsCatelogId;
	}
	public void setGoodsCatelogId(Integer goodsCatelogId)
	{
		this.goodsCatelogId = goodsCatelogId;
	}
	public String getGoodsDel()
	{
		return goodsDel;
	}
	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}
	
}